library(rvest)
library(tidyverse)
library(stringr)
library(magrittr)
library(purrr)
library(progress)
library(lubridate)
library(bigrquery)
library(parallel)
if (!dir.exists("data-raw")) dir.create("data-raw")

